# Generated by Django 4.2.5 on 2023-10-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class1', models.IntegerField(choices=[(7, 7), (8, 8), (9, 9)], verbose_name='class')),
                ('subject', models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biolodgy', 'Biolodgy')], max_length=20)),
                ('questiontype', models.CharField(choices=[('twomark', 'twomark'), ('threemark', 'threemark'), ('fivemark', 'fivemark')], max_length=20)),
                ('question', models.CharField(max_length=250)),
            ],
        ),
    ]
